### ISSUE TITLE
base url

### ISSUE THREAD

**Issue by iamciera** [ropensci-archive/reproducibility-guide#2]
For some reason I could not get the baseurl for the posts to work correctly.  So I cheated and added the projects name at all the links with the liquid tags {{ base.url }} should be.  Can anyone help?

**Comment by jhollist** [comment]
Not exactly sure, but in `_config.yml` it is currently set to `/test`.  My fork didn't work until I set it to root (i.e. `baseurl: /`).  I believe that since this is being served out of the gh-pages branch, the root would resolve at [`http://ropensci.github.io/reproducibility-guide`](http://ropensci.github.io/reproducibility-guide), which is what we want.

I am sure there are others with a lot more expertise than I who can weigh in.

**Comment by cboettig** [comment]
Yup, the github repo name (i.e. the local path) would be sufficient for hosting via gh-pages, `baseurl: /reproducibility-guide`, so that you could build the site locally and view it at (using the default build port) `localhost:4000/reproducibility-guide/index.html`, as well as online as @jhollist indicates.  

A quick glance shows that `index.html` isn't using `{{base.url}}` to link the posts though, and has hardwired `reproducibility-guide` before `{{post.url}}`.  Guess we should fix that too.

**Comment by iamciera** [comment]
Yeah.  I couldn't seem to get it to work in another repo so I hardwired all the links.  I changed it back to how I believe it _should_ work, which I believe is what you guys are talking about, but now the links don't work.

**Comment by jhollist** [comment]
I think I've got it.  I'll submit a PR shortly with

set `baseurl: /reproducibility-guide`

index.html with `{{ site.baseurl }}` instead of hardwired

default.html layout with home link pointing to the baseurl as well.
