### ISSUE TITLE
Add Karl's reproducibility stuff

### ISSUE THREAD

**Issue by karthik** [ropensci-archive/reproducibility-guide#29]
Another resource worth listing: https://github.com/kbroman/Tools4RR

@kbroman does fantastic things in this space and you guys should ask him to do a little review at some point.

**Comment by benmarwick** [comment]
Thanks, that is an excellent resource - we've already got it in the 'further reading' list. Would be great to have his input also.

**Comment by kbroman** [comment]
Thanks for the kind words. The reproducibility guide is a great idea; I'll be happy to participate in its development.

**Comment by iamciera** [comment]
@kbroman!  So cool.  Thanks!

**Comment by iamciera** [comment]
@kbroman,
I love all your tutorials! At the moment I am not sure how to incorporate tutorials into the site yet.  For now I think I will add them to a resources section on each page.  While the exact function of the site has been evolving, at the moment I think it is acting as a super brief introduction to the basics and hopefully a launching point to more in depth information on reproducibility.  Any thoughts you have on this are welcome.

One section of your tutorials would be great on the front page,  your [Contribute to someone's repository](http://kbroman.github.io/github_tutorial/pages/fork.html) section of your larger github tutorial.  I was thinking of creating a section just like to encourage collaboration by showing how easy it is to contribute, but you seemed to have done this beautifully.   Could we use the content directly on the site?  I would of course link to your original material.

**Comment by kbroman** [comment]
Thanks!

Yes feel free to incorporate any of my material in any way you wish. I licensed it CC-BY with the hope that it might be remixed and reused in the way you propose. 

(The material in my [Tools4RR](http://kbroman.github.io/Tools4RR/) course is CC0, which is the way I'm leaning now, so that then one can cite the source as convenient rather than in some rigorous way.)

Your plan sounds spot-on. I've become very enthusiastic about the concept of brief introductions with links to further resources, as you can see from my tutorials.
