### ISSUE TITLE
Add an Introduction and Definition of Reproducibility?

### ISSUE THREAD

**Issue by jhollist** [ropensci-archive/reproducibility-guide#4]
Would be nice to have some introductory materials/pre-amble to the guide that explains what the guide is and isn't.

Along those lines a working definition of reproducibility might be nice.   Looking back at hackathon issue [#22](https://github.com/ropensci/hackathon/issues/22) suggest that there is at least a gradient of reproducibility.  Much of our discussion (or at least my recollection of it) has centered around producing reproducible documents, but as many have indicated, reproducibility is a much larger issue than that.  

At a simple level as long as one has access to code/data/paper it could meet some minimum criteria of reproducibility.  The discussions on data archiving [#21](https://github.com/ropensci/hackathon/issues/21) and sustainability/versioning [#19](https://github.com/ropensci/hackathon/issues/19) bring up bigger issues that, if dealt with, would make a given piece of work a greater degree of reproducibility.  Lastly, @mfenner made the good point that to be fully reproducible [automation](https://github.com/ropensci/hackathon/issues/22) needs to be considered. 

I have done a (very) little work with Linked Open Data and as I have laid it out here it reminds me of the [5 star system](http://www.w3.org/DesignIssues/LinkedData.html) of Linked Open Data.  Would it be useful to think of reproducibility in the same terms?  Is that out of scope for this guide (quite possibly).  

In any event, I would find it useful if we could develop an introduction and specific definition about what type/level/etc of reproducibility  we are referring to.  Will help focus the rest of the guide, I think.

**Comment by benmarwick** [comment]
Great point about definitions and gradient. Roger Peng describes it as a spectrum, which I think is an excellent way to frame the topic, since it lowers the barrier to entry and accommodates a wide range of efforts supporting RR (for example where data can't be shared for privacy reasons, etc.). He has a nice graphic here Peng 2011, Science 334(6060) pp. 1226-1227

![peng](https://raw.githubusercontent.com/benmarwick/CSSS-Primer-Reproducible-Research/master/figures/peng-spectrum.jpg)

**Comment by cboettig** [comment]
Peng's graphic looks great, but I think that there more dimensions or elements that need to be included in the gradient.  It's really easy to "have" code + data and yet not be reproducible.  Reproducibility studies very frequently fail to run code provided, often do to problems with software dependencies, etc.  

For instance, check out Neil's recommendations and the practices recommended by the Software Sustanability Institute's software journal: https://github.com/mozillascience/code-research-object/issues/2#issuecomment-35610035

**Comment by benmarwick** [comment]
Agreed, it's much more complex, [this recent study](http://reproducibility.cs.arizona.edu/) is a great example of all the ways it can go wrong. The list you mention from @npch is a really excellent way to make a template or checklist for capturing basic details, we could build on that in the doc here. Dependencies is a very thorny problem, virtual machines is one rather bulky solution, [pakrat](http://rstudio.github.io/packrat/) seems to be a good start for the R ecosystem, any thoughts on how to communicate dependancies? 

http://researchcompendia.org/ is a promising tool that is planning to include some kind of code execution function, so you can run others' code and data in the browser. 

That said, I'm in the social sciences where point-and-click is the dominant workflow, so I'm happy to promote even the simplest and most elementary efforts towards RR, without exposing folks to too much of the complicating detail. In these cases have the code is a huge step forward because it makes the methods more transparent, even if the code cannot actually be run, we are still making progress by knowing more about how the results were achieved.
